# yaml file to deploy to kuberneties
# kubectl create -f marcread-k8.yml -f marcread-k8-np.yml


apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: marcread
  name: marcread-np
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: marcread
  type: NodePort
status:
  loadBalancer: {}